FROM ubuntu:18.04
RUN apt-get update && apt install -y wget build-essential clang
RUN wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
RUN chmod +x /usr/local/bin/bazel
COPY . /tmp
WORKDIR tmp
ENV GRPC_VERBOSITY=debug
ENTRYPOINT bazel run //test/e2e:e2e_consumer
