FROM ubuntu:22.04
RUN apt-get update && apt install -y build-essential clang git wget
RUN wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
RUN chmod +x /usr/local/bin/bazel
COPY . /tmp
WORKDIR /tmp
RUN bazel build //test/e2e:e2e_consumer
