load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "config_lib",
  hdrs = ["config_impl.h"],
  deps = [
    "//sky2cpp:config_interface",
  ],
  visibility = ["//visibility:public"],
)
